# Generated by Django 4.1.2 on 2022-11-02 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreHierarchy',
            fields=[
                ('genre', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='mainGenre', serialize=False, to='genres.genre')),
            ],
            options={
                'db_table': 'genre_hierarchy',
                'managed': False,
            },
        ),
    ]
