# Generated by Django 4.1.2 on 2022-10-27 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('favourite', models.BooleanField()),
                ('wikidata_id', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'track',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'track_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrackIsrc',
            fields=[
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tracks.track')),
                ('isrc', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'track_isrc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrackIswc',
            fields=[
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tracks.track')),
                ('iswc', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'track_iswc',
                'managed': False,
            },
        ),
    ]
