# Generated by Django 4.1.2 on 2022-10-27 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('formation_date', models.CharField(blank=True, max_length=10, null=True)),
                ('formation_area', models.TextField(blank=True, null=True)),
                ('disband_date', models.CharField(blank=True, max_length=10, null=True)),
                ('disband_area', models.TextField(blank=True, null=True)),
                ('favourite', models.BooleanField()),
                ('isni', models.CharField(blank=True, max_length=19, null=True, unique=True)),
                ('amazon_music_id', models.TextField(blank=True, null=True, unique=True)),
                ('wikidata_id', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'artist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArtistType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'artist_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ipi',
            fields=[
                ('ipi_id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ipi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArtistGenres',
            fields=[
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='artists.artist')),
            ],
            options={
                'db_table': 'artist_genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArtistIpis',
            fields=[
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='artists.artist')),
            ],
            options={
                'db_table': 'artist_ipis',
                'managed': False,
            },
        ),
    ]
