# Generated by Django 4.1.2 on 2022-10-27 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogue_id', models.TextField()),
            ],
            options={
                'db_table': 'catalogue_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('formation_date', models.CharField(blank=True, max_length=10, null=True)),
                ('formation_area', models.TextField(blank=True, null=True)),
                ('closing_date', models.CharField(blank=True, max_length=10, null=True)),
                ('favourite', models.BooleanField()),
                ('label_code', models.TextField(blank=True, null=True, unique=True)),
                ('wikidata_id', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'label',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogueMedia',
            fields=[
                ('global_catalogue', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='labels.catalogueitems')),
            ],
            options={
                'db_table': 'catalogue_media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LabelIpis',
            fields=[
                ('label', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='labels.label')),
            ],
            options={
                'db_table': 'label_ipis',
                'managed': False,
            },
        ),
    ]
