# Generated by Django 4.1.2 on 2022-10-27 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('birth_date', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_area', models.TextField(blank=True, null=True)),
                ('death_date', models.CharField(blank=True, max_length=10, null=True)),
                ('death_area', models.TextField(blank=True, null=True)),
                ('favourite', models.BooleanField()),
                ('isni', models.CharField(blank=True, max_length=19, null=True, unique=True)),
                ('wikidata_id', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'producer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProducerIpis',
            fields=[
                ('producer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='producers.producer')),
            ],
            options={
                'db_table': 'producer_ipis',
                'managed': False,
            },
        ),
    ]
